// ewb dummmy data
export const ewb_dummy_data = [
    {
        "data": {
            "ewbNo": 332270587038,
            "ewayBillDate": "12/06/2026 05:36:00 PM",
            "genMode": "WEB",
            "userGstin": "06AADCT6685Q1ZG",
            "supplyType": "O",
            "subSupplyType": "5  ",
            "docType": "CHL",
            "docNo": "26GPTFOC00465",
            "docDate": "12/06/2026",
            "fromGstin": "06AADCT6685Q1ZG",
            "fromTrdName": "TOYOTA MATERIAL HANDLING INDIA PVT. LTD.",
            "fromAddr1": "TOYOTA MATERIAL HANDLING INDIA PRIVATE LIMITED",
            "fromAddr2": "Mile Stone 43 Delhi-Jaipur HighwayNH-08",
            "fromPlace": "Gurugram",
            "fromPincode": 122004,
            "fromStateCode": 6,
            "toGstin": "06AADCT6685Q1ZG",
            "toTrdName": "TOYOTA MATERIAL HANDLING INDIA PVT. LTD.",
            "toAddr1": "TOYOTA MATERIAL HANDLING INDIA PRIVATE LIMITED",
            "toAddr2": "C/o YUSEN LOGISTICS INDIA PRIVATE LIMITED, VILLAGE UNCHA MAZRA, 19/4/1-7-7,, 4/2 -1-1- 5/1 -616, 5/2",
            "toPlace": "Ludhiana",
            "toPincode": 122503,
            "toStateCode": 6,
            "totalValue": 27487.00,
            "totInvValue": 32434.66,
            "cgstValue": 2473.83,
            "sgstValue": 2473.83,
            "igstValue": 0.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 27,
            "noValidDays": 1,
            "validUpto": "13/06/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 6,
            "actToStateCode": 6,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 85122020,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 6668.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84312090,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 6484.00
                },
                {
                    "itemNo": 3,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 85122020,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 13134.00
                },
                {
                    "itemNo": 4,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 85443000,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 1201.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "DL01LY2650",
                    "fromPlace": "GURGAON",
                    "fromState": 6,
                    "tripshtNo": 3158303612,
                    "userGSTINTransin": "06CNNPS9713A1ZT",
                    "enteredDate": "13/06/2026 09:42:00 AM",
                    "transMode": "1",
                    "transDocNo": "ASPERLR",
                    "transDocDate": "13/06/2026",
                    "groupNo": "0"
                },
                {
                    "updMode": "WEB",
                    "vehicleNo": "HR55AJ1631",
                    "fromPlace": "Gurugram",
                    "fromState": 6,
                    "tripshtNo": 0,
                    "userGSTINTransin": "06AADCT6685Q1ZG",
                    "enteredDate": "12/06/2026 05:36:00 PM",
                    "transMode": "1",
                    "transDocNo": "ASPERLR",
                    "transDocDate": "12/06/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "QwVTVdLOUgYlyCFqHL0bcNQp3PDzvd1aI1HYfQ0qxpuVBNcw-mtdFA==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    },
    {
        "data": {
            "ewbNo": 441381698149,
            "ewayBillDate": "18/06/2026 11:15:00 AM",
            "genMode": "WEB",
            "userGstin": "09AADCT6685Q1UU",
            "supplyType": "I",
            "subSupplyType": "1  ",
            "docType": "INV",
            "docNo": "MH2026INV00812",
            "docDate": "18/06/2026",
            "fromGstin": "09AADCT6685Q1OR",
            "fromTrdName": "MAHINDRA LOGISTICS LTD.",
            "fromAddr1": "MAHINDRA LOGISTICS LIMITED",
            "fromAddr2": "Plot No. 25, Sector 18, Gurugram Industrial Area",
            "fromPlace": "Faridabad",
            "fromPincode": 121001,
            "fromStateCode": 6,
            "toGstin": "09AADCT6685Q1EE",
            "toTrdName": "MAHINDRA LOGISTICS LTD.",
            "toAddr1": "MAHINDRA LOGISTICS LIMITED",
            "toAddr2": "C/o BLUE DART EXPRESS LTD, NH-48, VILLAGE KHERKI DAULA, SECTOR 37",
            "toPlace": "Manesar",
            "toPincode": 122051,
            "toStateCode": 6,
            "totalValue": 41250.00,
            "totInvValue": 48675.00,
            "cgstValue": 3712.50,
            "sgstValue": 3712.50,
            "igstValue": 0.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 42,
            "noValidDays": 1,
            "validUpto": "19/06/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 6,
            "actToStateCode": 6,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 87089900,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 18500.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84073490,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 22750.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "HR26BX4412",
                    "fromPlace": "FARIDABAD",
                    "fromState": 6,
                    "tripshtNo": 4271904823,
                    "userGSTINTransin": "09AADCT6685Q1MN",
                    "enteredDate": "18/06/2026 11:15:00 AM",
                    "transMode": "1",
                    "transDocNo": "MLBLR2026",
                    "transDocDate": "18/06/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Xx9KLmNpQrStUvWxYz1234AbCdEfGhIjKlMnOpQrStUvWxYz12==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    },
    {
        "data": {
            "ewbNo": 557492809260,
            "ewayBillDate": "25/06/2026 02:48:00 PM",
            "genMode": "WEB",
            "userGstin": "98AADCT6685Q1JO",
            "supplyType": "O",
            "subSupplyType": "3  ",
            "docType": "INV",
            "docNo": "DL2026EXP01133",
            "docDate": "25/06/2026",
            "fromGstin": "98AADCT6685Q1JO",
            "fromTrdName": "BLUEDART EXPRESS PVT. LTD.",
            "fromAddr1": "BLUEDART EXPRESS PRIVATE LIMITED",
            "fromAddr2": "Plot No. 7, Phase II, Udyog Vihar, Gurugram",
            "fromPlace": "Delhi",
            "fromPincode": 110020,
            "fromStateCode": 7,
            "toGstin": "98AADCT6685Q1JO",
            "toTrdName": "BLUEDART EXPRESS PVT. LTD.",
            "toAddr1": "BLUEDART EXPRESS PRIVATE LIMITED",
            "toAddr2": "Warehouse No. 3, IMT Manesar, Sector 8, Haryana",
            "toPlace": "Rewari",
            "toPincode": 123401,
            "toStateCode": 6,
            "totalValue": 15800.00,
            "totInvValue": 18644.00,
            "cgstValue": 0.00,
            "sgstValue": 0.00,
            "igstValue": 2844.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 85,
            "noValidDays": 1,
            "validUpto": "26/06/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 7,
            "actToStateCode": 6,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 90189099,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 9200.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84552290,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 6600.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "DL8CX9901",
                    "fromPlace": "DELHI",
                    "fromState": 7,
                    "tripshtNo": 6384715290,
                    "userGSTINTransin": "98AADCT6685Q1JO",
                    "enteredDate": "25/06/2026 02:48:00 PM",
                    "transMode": "1",
                    "transDocNo": "BDEXP2026",
                    "transDocDate": "25/06/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Pp7QrStUvWxYzAbCdEfGhIj5678KlMnOpQrStUvWxYzAbCdEf==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    },
    {
        "data": {
            "ewbNo": 141092837482,
            "ewayBillDate": "12/09/2026 10:15:00 AM",
            "genMode": "API",
            "userGstin": "27AAACB1234A1Z5",
            "supplyType": "O",
            "subSupplyType": "1",
            "docType": "INV",
            "docNo": "INV/2026-27/0451",
            "docDate": "12/09/2026",
            "fromGstin": "27AAACB1234A1Z5",
            "fromTrdName": "TECH SUPPLIES INDIA LTD",
            "fromAddr1": "Plot 42, MIDC Industrial Area",
            "fromAddr2": "Andheri East",
            "fromPlace": "Mumbai",
            "fromPincode": 400093,
            "fromStateCode": 27,
            "toGstin": "27AABCC5678B1Z2",
            "toTrdName": "INFOTECH SYSTEMS PVT LTD",
            "toAddr1": "Building B, IT Park",
            "toAddr2": "Hinjewadi Phase 1",
            "toPlace": "Pune",
            "toPincode": 411057,
            "toStateCode": 27,
            "totalValue": 50000.00,
            "totInvValue": 59000.00,
            "cgstValue": 4500.00,
            "sgstValue": 4500.00,
            "igstValue": 0.00,
            "cessValue": 0.00,
            "transporterId": "27AABCT9988C1Z3",
            "transporterName": "MAHARASHTRA LOGISTICS PVT LTD",
            "status": "ACT",
            "actualDist": 150,
            "noValidDays": 1,
            "validUpto": "13/09/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 27,
            "actToStateCode": 27,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
            {
                "itemNo": 1,
                "productId": 101,
                "productName": "Computer Hardware",
                "productDesc": "Dell Monitors 27 Inch",
                "hsnCode": 84716060,
                "quantity": 5.00,
                "qtyUnit": "NOS",
                "cgstRate": 9.000,
                "sgstRate": 9.000,
                "igstRate": 0.000,
                "cessRate": 0.000,
                "cessNonAdvol": 0.00,
                "taxableAmount": 50000.00
            }
            ],
            "VehiclListDetails": [
            {
                "updMode": "API",
                "vehicleNo": "MH12AB1234",
                "fromPlace": "MUMBAI",
                "fromState": 27,
                "tripshtNo": 7788990011,
                "userGSTINTransin": "27AAACB1234A1Z5",
                "enteredDate": "12/09/2026 10:15:00 AM",
                "transMode": "1",
                "transDocNo": "LR109283",
                "transDocDate": "12/09/2026",
                "groupNo": "0"
            }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "27AAACB1234A1Z5",
            "client_secret": "EWBPa1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "via": "2.0 123a45bce6d7e8901c23e456aec7890.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Aa1Bb2Cc3Dd4Ee5Ff6Gg7Hh8Ii9Jj0Kk1Ll2Mm3Nn4Oo5Pp==",
            "client_id": "EWBPa1b2c3d4-e5f6-7890-abcd-1234567890ab",
            "ip_address": "103.22.140.12"
        }
    },
    {
        "data": {
            "ewbNo": 883920192847,
            "ewayBillDate": "18/09/2026 04:30:00 PM",
            "genMode": "WEB",
            "userGstin": "29AAACC9876F1Z1",
            "supplyType": "O",
            "subSupplyType": "1",
            "docType": "INV",
            "docNo": "KA/2026/9982",
            "docDate": "18/09/2026",
            "fromGstin": "29AAACC9876F1Z1",
            "fromTrdName": "KARNATAKA TEXTILE MILLS",
            "fromAddr1": "No 12, Peenya Industrial Area",
            "fromAddr2": "3rd Stage, Peenya",
            "fromPlace": "Bengaluru",
            "fromPincode": 560058,
            "fromStateCode": 29,
            "toGstin": "33AABCF4321D1Z9",
            "toTrdName": "TAMILNADU GARMENTS PVT LTD",
            "toAddr1": "45, Avinashi Road",
            "toAddr2": "Near Hope College",
            "toPlace": "Coimbatore",
            "toPincode": 641004,
            "toStateCode": 33,
            "totalValue": 120000.00,
            "totInvValue": 126000.00,
            "cgstValue": 0.00,
            "sgstValue": 0.00,
            "igstValue": 6000.00,
            "cessValue": 0.00,
            "transporterId": "29AAACT1122D1Z0",
            "transporterName": "SOUTH FREIGHT EXPRESS",
            "status": "ACT",
            "actualDist": 365,
            "noValidDays": 2,
            "validUpto": "20/09/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 29,
            "actToStateCode": 33,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
            {
                "itemNo": 1,
                "productId": 204,
                "productName": "Cotton Fabric",
                "productDesc": "100% Woven Cotton Roll",
                "hsnCode": 52081190,
                "quantity": 1000.00,
                "qtyUnit": "MTR",
                "cgstRate": 0.000,
                "sgstRate": 0.000,
                "igstRate": 5.000,
                "cessRate": 0.000,
                "cessNonAdvol": 0.00,
                "taxableAmount": 120000.00
            }
            ],
            "VehiclListDetails": [
            {
                "updMode": "WEB",
                "vehicleNo": "KA04CD5678",
                "fromPlace": "BENGALURU",
                "fromState": 29,
                "tripshtNo": 8829102938,
                "userGSTINTransin": "29AAACC9876F1Z1",
                "enteredDate": "18/09/2026 04:30:00 PM",
                "transMode": "1",
                "transDocNo": "SFE/2026/881",
                "transDocDate": "18/09/2026",
                "groupNo": "0"
            }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "29AAACC9876F1Z1",
            "client_secret": "EWBPa9876543-b210-4567-89ab-cdef01234567",
            "via": "2.0 456b78cde9f01d234e567890abc1234.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Bb2Cc3Dd4Ee5Ff6Gg7Hh8Ii9Jj0Kk1Ll2Mm3Nn4Oo5Pp6Qq==",
            "client_id": "EWBPa9876543-b210-4567-89ab-9876543210fe",
            "ip_address": "49.207.210.4"
        }
    },
    {
        "data": {
            "ewbNo": 339102847561,
            "ewayBillDate": "22/09/2026 01:10:00 PM",
            "genMode": "API",
            "userGstin": "07AAACG5544H1Z8",
            "supplyType": "O",
            "subSupplyType": "4",
            "docType": "CHL",
            "docNo": "DC/JW/2026/089",
            "docDate": "22/09/2026",
            "fromGstin": "07AAACG5544H1Z8",
            "fromTrdName": "DELHI AUTO COMPONENTS PVT LTD",
            "fromAddr1": "Plot 18, Okhla Industrial Estate",
            "fromAddr2": "Phase 3",
            "fromPlace": "New Delhi",
            "fromPincode": 110020,
            "fromStateCode": 7,
            "toGstin": "09AAACK3322J1Z3",
            "toTrdName": "UP PRECISION TOOLS",
            "toAddr1": "B-14, Sector 63",
            "toAddr2": "Gautam Buddha Nagar",
            "toPlace": "Noida",
            "toPincode": 201301,
            "toStateCode": 9,
            "totalValue": 85000.00,
            "totInvValue": 100300.00,
            "cgstValue": 0.00,
            "sgstValue": 0.00,
            "igstValue": 15300.00,
            "cessValue": 0.00,
            "transporterId": "07AAACT0011E1Z4",
            "transporterName": "CAPITAL LOGISTICS INDIA",
            "status": "ACT",
            "actualDist": 42,
            "noValidDays": 1,
            "validUpto": "23/09/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 7,
            "actToStateCode": 9,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
            {
                "itemNo": 1,
                "productId": 501,
                "productName": "Steel Shafts",
                "productDesc": "Raw Machined Shafts",
                "hsnCode": 73269099,
                "quantity": 250.00,
                "qtyUnit": "KGS",
                "cgstRate": 0.000,
                "sgstRate": 0.000,
                "igstRate": 18.000,
                "cessRate": 0.000,
                "cessNonAdvol": 0.00,
                "taxableAmount": 50000.00
            },
            {
                "itemNo": 2,
                "productId": 502,
                "productName": "Aluminum Bearings",
                "productDesc": "Industrial Grade Bearings",
                "hsnCode": 84821010,
                "quantity": 100.00,
                "qtyUnit": "NOS",
                "cgstRate": 0.000,
                "sgstRate": 0.000,
                "igstRate": 18.000,
                "cessRate": 0.000,
                "cessNonAdvol": 0.00,
                "taxableAmount": 35000.00
            }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "API",
                    "vehicleNo": "DL1GC4321",
                    "fromPlace": "NEW DELHI",
                    "fromState": 7,
                    "tripshtNo": 5544332211,
                    "userGSTINTransin": "07AAACG5544H1Z8",
                    "enteredDate": "22/09/2026 01:10:00 PM",
                    "transMode": "1",
                    "transDocNo": "CLI-2026-90",
                    "transDocDate": "22/09/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "07AAACG5544H1Z8",
            "client_secret": "EWBPf5e4d3c2-b1a0-9876-5432-10fedcba9876",
            "via": "2.0 789c01def2a34b567890c123def4567.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Cc3Dd4Ee5Ff6Gg7Hh8Ii9Jj0Kk1Ll2Mm3Nn4Oo5Pp6Qq7Rr==",
            "client_id": "EWBPf5e4d3c2-b1a0-9876-5432-0987654321dc",
            "ip_address": "122.160.180.22"
        }
    },
    {
        "data": {
            "ewbNo": 992018273645,
            "ewayBillDate": "23/09/2026 03:30:00 PM",
            "genMode": "API",
            "userGstin": "27AAACB1234A1Z5",
            "supplyType": "O",
            "subSupplyType": "5",
            "docType": "CHL",
            "docNo": "ST/2026-27/0082",
            "docDate": "23/09/2026",
            "fromGstin": "27AAACB1234A1Z5",
            "fromTrdName": "TECH SUPPLIES INDIA LTD",
            "fromAddr1": "Plot 42, MIDC Industrial Area",
            "fromAddr2": "Central Warehouse, Andheri East",
            "fromPlace": "Mumbai",
            "fromPincode": 400093,
            "fromStateCode": 27,
            "toGstin": "27AAACB1234A1Z5",
            "toTrdName": "TECH SUPPLIES INDIA LTD",
            "toAddr1": "Depot No. 5, Logistics Park",
            "toAddr2": "Bhiwandi-Kalyan Road",
            "toPlace": "Bhiwandi",
            "toPincode": 421302,
            "toStateCode": 27,
            "totalValue": 75000.00,
            "totInvValue": 88500.00,
            "cgstValue": 6750.00,
            "sgstValue": 6750.00,
            "igstValue": 0.00,
            "cessValue": 0.00,
            "transporterId": "27AABCT9988C1Z3",
            "transporterName": "MAHARASHTRA LOGISTICS PVT LTD",
            "status": "ACT",
            "actualDist": 45,
            "noValidDays": 1,
            "validUpto": "24/09/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 27,
            "actToStateCode": 27,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
            {
                "itemNo": 1,
                "productId": 102,
                "productName": "Networking Equipment",
                "productDesc": "Enterprise Rack Switches",
                "hsnCode": 85176290,
                "quantity": 10.00,
                "qtyUnit": "NOS",
                "cgstRate": 9.000,
                "sgstRate": 9.000,
                "igstRate": 0.000,
                "cessRate": 0.000,
                "cessNonAdvol": 0.00,
                "taxableAmount": 75000.00
            }
            ],
            "VehiclListDetails": [
            {
                "updMode": "API",
                "vehicleNo": "MH04CD9876",
                "fromPlace": "MUMBAI",
                "fromState": 27,
                "tripshtNo": 9988776655,
                "userGSTINTransin": "27AAACB1234A1Z5",
                "enteredDate": "23/09/2026 03:30:00 PM",
                "transMode": "1",
                "transDocNo": "DC/ST/9021",
                "transDocDate": "23/09/2026",
                "groupNo": "0"
            }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "27AAACB1234A1Z5",
            "client_secret": "EWBPa1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "via": "2.0 123a45bce6d7e8901c23e456aec7890.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Xx9Yy8Zz7Aa6Bb5Cc4Dd3Ee2Ff1Gg0Hh1Ii2Jj3Kk4Ll==",
            "client_id": "EWBPa1b2c3d4-e5f6-7890-abcd-1234567890ab",
            "ip_address": "103.22.140.12"
        }
    },
    
    {
        "data": {
            "ewbNo": 668503920174,
            "ewayBillDate": "28/09/2026 09:00:00 AM",
            "genMode": "WEB",
            "userGstin": "06AADCT6685Q1ZG",
            "supplyType": "O",
            "subSupplyType": "5  ",
            "docType": "CHL",
            "docNo": "26GPTFOC00521",
            "docDate": "28/09/2026",
            "fromGstin": "06AADCT6685Q1ZG",
            "fromTrdName": "TOYOTA MATERIAL HANDLING INDIA PVT. LTD.",
            "fromAddr1": "TOYOTA MATERIAL HANDLING INDIA PRIVATE LIMITED",
            "fromAddr2": "Mile Stone 43 Delhi-Jaipur Highway NH-08",
            "fromPlace": "Gurugram",
            "fromPincode": 122004,
            "fromStateCode": 6,
            "toGstin": "06AADCT6685Q1ZG",
            "toTrdName": "TOYOTA MATERIAL HANDLING INDIA PVT. LTD.",
            "toAddr1": "TOYOTA MATERIAL HANDLING INDIA PRIVATE LIMITED",
            "toAddr2": "Industrial Area Phase 1, Focal Point, Ludhiana",
            "toPlace": "Ludhiana",
            "toPincode": 141001,
            "toStateCode": 3,
            "totalValue": 32000.00,
            "totInvValue": 37760.00,
            "cgstValue": 0.00,
            "sgstValue": 0.00,
            "igstValue": 5760.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 310,
            "noValidDays": 2,
            "validUpto": "30/09/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 6,
            "actToStateCode": 3,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 85122020,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 14800.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84312090,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 17200.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "HR55BK3872",
                    "fromPlace": "GURUGRAM",
                    "fromState": 6,
                    "tripshtNo": 7710293846,
                    "userGSTINTransin": "06AADCT6685Q1ZG",
                    "enteredDate": "28/09/2026 09:00:00 AM",
                    "transMode": "1",
                    "transDocNo": "ASPERLR",
                    "transDocDate": "28/09/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Rr8Ss9Tt0Uu1Vv2Ww3Xx4Yy5Zz6Aa7Bb8Cc9Dd0Ee1Ff2Gg==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    },
    {
        "data": {
            "ewbNo": 775614031285,
            "ewayBillDate": "28/09/2026 02:15:00 PM",
            "genMode": "WEB",
            "userGstin": "09AADCT6685Q1UU",
            "supplyType": "I",
            "subSupplyType": "1  ",
            "docType": "INV",
            "docNo": "MH2026INV00934",
            "docDate": "28/09/2026",
            "fromGstin": "09AADCT6685Q1OR",
            "fromTrdName": "MAHINDRA LOGISTICS LTD.",
            "fromAddr1": "MAHINDRA LOGISTICS LIMITED",
            "fromAddr2": "Plot No. 25, Sector 18, Gurugram Industrial Area",
            "fromPlace": "Gurugram",
            "fromPincode": 122001,
            "fromStateCode": 6,
            "toGstin": "09AADCT6685Q1EE",
            "toTrdName": "MAHINDRA LOGISTICS LTD.",
            "toAddr1": "MAHINDRA LOGISTICS LIMITED",
            "toAddr2": "C/o DELHIVERY LTD, G.T. Road, Ludhiana Industrial Area",
            "toPlace": "Ludhiana",
            "toPincode": 141001,
            "toStateCode": 3,
            "totalValue": 55000.00,
            "totInvValue": 64900.00,
            "cgstValue": 0.00,
            "sgstValue": 0.00,
            "igstValue": 9900.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 310,
            "noValidDays": 2,
            "validUpto": "30/09/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 6,
            "actToStateCode": 3,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 87089900,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 28000.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84073490,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 27000.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "HR26DM7741",
                    "fromPlace": "GURUGRAM",
                    "fromState": 6,
                    "tripshtNo": 8821039475,
                    "userGSTINTransin": "09AADCT6685Q1MN",
                    "enteredDate": "28/09/2026 02:15:00 PM",
                    "transMode": "1",
                    "transDocNo": "MLBLR2026",
                    "transDocDate": "28/09/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Ss9Tt0Uu1Vv2Ww3Xx4Yy5Zz6Aa7Bb8Cc9Dd0Ee1Ff2Gg3Hh==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    }
];