// ewb dummmy data
export const ewb_dummy_data = [
    {
        "data": {
            "ewbNo": 332270587038,
            "ewayBillDate": "12/06/2026 05:36:00 PM",
            "genMode": "WEB",
            "userGstin": "06AADCT6685Q1ZG",
            "supplyType": "O",
            "subSupplyType": "5  ",
            "docType": "CHL",
            "docNo": "26GPTFOC00465",
            "docDate": "12/06/2026",
            "fromGstin": "06AADCT6685Q1ZG",
            "fromTrdName": "TOYOTA MATERIAL HANDLING INDIA PVT. LTD.",
            "fromAddr1": "TOYOTA MATERIAL HANDLING INDIA PRIVATE LIMITED",
            "fromAddr2": "Mile Stone 43 Delhi-Jaipur HighwayNH-08",
            "fromPlace": "Gurugram",
            "fromPincode": 122004,
            "fromStateCode": 6,
            "toGstin": "06AADCT6685Q1ZG",
            "toTrdName": "TOYOTA MATERIAL HANDLING INDIA PVT. LTD.",
            "toAddr1": "TOYOTA MATERIAL HANDLING INDIA PRIVATE LIMITED",
            "toAddr2": "C/o YUSEN LOGISTICS INDIA PRIVATE LIMITED, VILLAGE UNCHA MAZRA, 19/4/1-7-7,, 4/2 -1-1- 5/1 -616, 5/2",
            "toPlace": "PATAUDI",
            "toPincode": 122503,
            "toStateCode": 6,
            "totalValue": 27487.00,
            "totInvValue": 32434.66,
            "cgstValue": 2473.83,
            "sgstValue": 2473.83,
            "igstValue": 0.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 27,
            "noValidDays": 1,
            "validUpto": "13/06/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 6,
            "actToStateCode": 6,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 85122020,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 6668.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84312090,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 6484.00
                },
                {
                    "itemNo": 3,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 85122020,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 13134.00
                },
                {
                    "itemNo": 4,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 85443000,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 1201.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "DL01LY2650",
                    "fromPlace": "GURGAON",
                    "fromState": 6,
                    "tripshtNo": 3158303612,
                    "userGSTINTransin": "06CNNPS9713A1ZT",
                    "enteredDate": "13/06/2026 09:42:00 AM",
                    "transMode": "1",
                    "transDocNo": "ASPERLR",
                    "transDocDate": "13/06/2026",
                    "groupNo": "0"
                },
                {
                    "updMode": "WEB",
                    "vehicleNo": "HR55AJ1631",
                    "fromPlace": "Gurugram",
                    "fromState": 6,
                    "tripshtNo": 0,
                    "userGSTINTransin": "06AADCT6685Q1ZG",
                    "enteredDate": "12/06/2026 05:36:00 PM",
                    "transMode": "1",
                    "transDocNo": "ASPERLR",
                    "transDocDate": "12/06/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "QwVTVdLOUgYlyCFqHL0bcNQp3PDzvd1aI1HYfQ0qxpuVBNcw-mtdFA==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    },
    {
        "data": {
            "ewbNo": 441381698149,
            "ewayBillDate": "18/06/2026 11:15:00 AM",
            "genMode": "WEB",
            "userGstin": "09AADCT6685Q1MN",
            "supplyType": "I",
            "subSupplyType": "1  ",
            "docType": "INV",
            "docNo": "MH2026INV00812",
            "docDate": "18/06/2026",
            "fromGstin": "09AADCT6685Q1MN",
            "fromTrdName": "MAHINDRA LOGISTICS LTD.",
            "fromAddr1": "MAHINDRA LOGISTICS LIMITED",
            "fromAddr2": "Plot No. 25, Sector 18, Gurugram Industrial Area",
            "fromPlace": "Faridabad",
            "fromPincode": 121001,
            "fromStateCode": 6,
            "toGstin": "09AADCT6685Q1MN",
            "toTrdName": "MAHINDRA LOGISTICS LTD.",
            "toAddr1": "MAHINDRA LOGISTICS LIMITED",
            "toAddr2": "C/o BLUE DART EXPRESS LTD, NH-48, VILLAGE KHERKI DAULA, SECTOR 37",
            "toPlace": "Manesar",
            "toPincode": 122051,
            "toStateCode": 6,
            "totalValue": 41250.00,
            "totInvValue": 48675.00,
            "cgstValue": 3712.50,
            "sgstValue": 3712.50,
            "igstValue": 0.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 42,
            "noValidDays": 1,
            "validUpto": "19/06/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 6,
            "actToStateCode": 6,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 87089900,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 18500.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84073490,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 9.000,
                    "sgstRate": 9.000,
                    "igstRate": -1.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 22750.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "HR26BX4412",
                    "fromPlace": "FARIDABAD",
                    "fromState": 6,
                    "tripshtNo": 4271904823,
                    "userGSTINTransin": "09AADCT6685Q1MN",
                    "enteredDate": "18/06/2026 11:15:00 AM",
                    "transMode": "1",
                    "transDocNo": "MLBLR2026",
                    "transDocDate": "18/06/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Xx9KLmNpQrStUvWxYz1234AbCdEfGhIjKlMnOpQrStUvWxYz12==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    },
    {
        "data": {
            "ewbNo": 557492809260,
            "ewayBillDate": "25/06/2026 02:48:00 PM",
            "genMode": "WEB",
            "userGstin": "98AADCT6685Q1JO",
            "supplyType": "O",
            "subSupplyType": "3  ",
            "docType": "INV",
            "docNo": "DL2026EXP01133",
            "docDate": "25/06/2026",
            "fromGstin": "98AADCT6685Q1JO",
            "fromTrdName": "BLUEDART EXPRESS PVT. LTD.",
            "fromAddr1": "BLUEDART EXPRESS PRIVATE LIMITED",
            "fromAddr2": "Plot No. 7, Phase II, Udyog Vihar, Gurugram",
            "fromPlace": "Delhi",
            "fromPincode": 110020,
            "fromStateCode": 7,
            "toGstin": "98AADCT6685Q1JO",
            "toTrdName": "BLUEDART EXPRESS PVT. LTD.",
            "toAddr1": "BLUEDART EXPRESS PRIVATE LIMITED",
            "toAddr2": "Warehouse No. 3, IMT Manesar, Sector 8, Haryana",
            "toPlace": "Rewari",
            "toPincode": 123401,
            "toStateCode": 6,
            "totalValue": 15800.00,
            "totInvValue": 18644.00,
            "cgstValue": 0.00,
            "sgstValue": 0.00,
            "igstValue": 2844.00,
            "cessValue": 0.00,
            "transporterId": "06AANCC0172H1ZS",
            "transporterName": "CARGOYAAN XPRESS PRIVATE LIMITED",
            "status": "ACT",
            "actualDist": 85,
            "noValidDays": 1,
            "validUpto": "26/06/2026 11:59:00 PM",
            "extendedTimes": 0,
            "rejectStatus": "N",
            "vehicleType": "R",
            "actFromStateCode": 7,
            "actToStateCode": 6,
            "transactionType": 1,
            "otherValue": 0.00,
            "cessNonAdvolValue": 0.00,
            "itemList": [
                {
                    "itemNo": 1,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 90189099,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 9200.00
                },
                {
                    "itemNo": 2,
                    "productId": 0,
                    "productName": "",
                    "productDesc": "",
                    "hsnCode": 84552290,
                    "quantity": 0.00,
                    "qtyUnit": "   ",
                    "cgstRate": 0.000,
                    "sgstRate": 0.000,
                    "igstRate": 18.000,
                    "cessRate": -1.000,
                    "cessNonAdvol": 0.00,
                    "taxableAmount": 6600.00
                }
            ],
            "VehiclListDetails": [
                {
                    "updMode": "WEB",
                    "vehicleNo": "DL8CX9901",
                    "fromPlace": "DELHI",
                    "fromState": 7,
                    "tripshtNo": 6384715290,
                    "userGSTINTransin": "98AADCT6685Q1JO",
                    "enteredDate": "25/06/2026 02:48:00 PM",
                    "transMode": "1",
                    "transDocNo": "BDEXP2026",
                    "transDocDate": "25/06/2026",
                    "groupNo": "0"
                }
            ]
        },
        "status_cd": "1",
        "status_desc": "EWAYBILL request succeeds",
        "header": {
            "gstin": "06AANCC0172H1ZS",
            "client_secret": "EWBPba531f90-bae9-420e-9a5b-7f4a87e73f03",
            "via": "2.0 389c05fcee7d9d909c44e981aec88496.cloudfront.net (CloudFront)",
            "x-amz-cf-id": "Pp7QrStUvWxYzAbCdEfGhIj5678KlMnOpQrStUvWxYzAbCdEf==",
            "client_id": "EWBP42c05bd4-f7a7-456d-b5b2-b043c79d7b74",
            "ip_address": "198.38.86.85"
        }
    }
];