ALTER TABLE sss.ssm_menu
  ADD COLUMN IF NOT EXISTS record_status int4 DEFAULT 0 NULL,
  ADD COLUMN IF NOT EXISTS created_by    int8 NULL,
  ADD COLUMN IF NOT EXISTS created_on    timestamp DEFAULT CURRENT_TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS updated_by    int8 NULL,
  ADD COLUMN IF NOT EXISTS updated_on    timestamp DEFAULT CURRENT_TIMESTAMP NULL;
