BEGIN;

ALTER TABLE sss.sst_docket
    ADD COLUMN IF NOT EXISTS dim_unit    VARCHAR(10)    DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS dim_length  NUMERIC(10,2)  DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS dim_breadth NUMERIC(10,2)  DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS dim_height  NUMERIC(10,2)  DEFAULT NULL;

COMMIT;
