const express = require('express');
const router = express.Router();
const ZoneMasterController = require('./zoneMaster.controller');

/* GET /zone — list all zones (optionally ?loc_code=&cust_code= filters) */
router.get('/', async (req, res) => {
    try {
        const tenant_id = req.tenant_id;
        let data = await ZoneMasterController.getAllZoneData(tenant_id);

        const { loc_code, cust_code } = req.query;
        if (loc_code) data = data.filter((z) => String(z.loc_code) === String(loc_code));
        if (cust_code) data = data.filter((z) => String(z.cust_code) === String(cust_code));

        res.status(200).json({ success: true, data });
    } catch (error) {
        console.error('Zone Master error:', error);
        res.status(500).json({ success: false, message: 'Error retrieving zone data' });
    }
});

/* GET /zone/:recId — single zone by record_id */
router.get('/:recId', async (req, res) => {
    try {
        const { recId } = req.params;
        const tenant_id = req.tenant_id;
        const data = await ZoneMasterController.getZoneDataByRecId(recId, tenant_id);
        if (!data) {
            return res.status(404).json({ success: false, message: 'Zone data not found' });
        }
        res.status(200).json({ success: true, data });
    } catch (error) {
        console.error('Zone Master error:', error);
        res.status(500).json({ success: false, message: 'Error retrieving zone data' });
    }
});

/* POST /zone — create zone; zone_code auto-generated by DB sequence */
router.post('/', async (req, res) => {
    try {
        const userId = req.user?.userId || null;
        const tenant_id = req.tenant_id;
        if (!tenant_id) {
            return res.status(400).json({ success: false, message: 'Tenant information missing from token' });
        }
        const payload = { ...req.body, tenant_id };
        const data = await ZoneMasterController.saveZoneData(userId, payload);
        res.status(201).json({ success: true, data });
    } catch (error) {
        console.error('Zone Master error:', error);
        res.status(500).json({ success: false, message: 'Error saving zone data' });
    }
});

/* PUT /zone/:recId — update zone by record_id */
router.put('/:recId', async (req, res) => {
    try {
        const { recId } = req.params;
        const userId = req.user?.userId || null;
        const tenant_id = req.tenant_id;
        const data = await ZoneMasterController.updateZoneData(recId, req.body, tenant_id, userId);
        if (!data || data.length === 0) {
            return res.status(404).json({ success: false, message: 'Zone data not found' });
        }
        res.status(200).json({ success: true, data });
    } catch (error) {
        console.error('Zone Master error:', error);
        res.status(500).json({ success: false, message: 'Error updating zone data' });
    }
});

/* DELETE /zone/:recId — delete zone by record_id */
router.delete('/:recId', async (req, res) => {
    try {
        const { recId } = req.params;
        const tenant_id = req.tenant_id;
        const deletedCount = await ZoneMasterController.deleteZoneData(recId, tenant_id);
        if (!deletedCount) {
            return res.status(404).json({ success: false, message: 'Zone data not found' });
        }
        res.status(200).json({ success: true, message: 'Zone data deleted successfully' });
    } catch (error) {
        console.error('Zone Master error:', error);
        res.status(500).json({ success: false, message: 'Error deleting zone data' });
    }
});

module.exports = router;
